---
- name: Create cache directory
  file:
    path: /var/cache/debconf-video-blackmagic
    state: directory

- name: Download Blackmagic Destkop Video package
  get_url:
    dest: /var/cache/debconf-video-blackmagic/desktopvideo.deb
    url: "{{ blackmagic.desktopvideo }}"

- name: Download Blackmagic Destkop Video GUI package
  get_url:
    dest: /var/cache/debconf-video-blackmagic/desktopvideo-gui.deb
    url: "{{ blackmagic.desktopvideo_gui }}"

- name: Download Blackmagic Media Express package
  get_url:
    dest: /var/cache/debconf-video-blackmagic/mediaexpress.deb
    url: "{{ blackmagic.desktopvideo }}"

- name: Install debs
  apt:
    deb: /var/cache/{{ item }}
  with_items:
    - debconf-video-blackmagic/desktopvideo.deb
    # - debconf-video-blackmagic/desktopvideo-gui.deb
    - debconf-video-blackmagic/mediaexpress.deb

- name: Install blackmagic DKMS driver
  command: dkms install {{ item }}/{{ blackmagic.dkms_version }}
  args:
    creates: /lib/modules/{{ ansible_kernel }}/updates/dkms/{{ item }}.ko
  with_items:
  - blackmagic
  - blackmagic-io
  when: ansible_env.ANSIBLE_UNDER_DI is undefined
